import type { Transaction } from './types'

export const transactions: readonly Transaction[] = [
  {
    id: 'emma-richardson-2024-08-29',
    recipient: 'Emma Richardson',
    category: 'Entertainment',
    date: new Date('2024-08-29'),
    amount: 75.5,
    avatarPath: '/profilePictures/Logo-1.jpg',
  },
  {
    id: 'bravo-zen-spa-2024-08-29',
    recipient: 'Bravo Zen Spa',
    category: 'Personal Care',
    date: new Date('2024-08-29'),
    amount: -25,
    avatarPath: '/profilePictures/Logo-1.jpg',
  },
  {
    id: 'savory-bites-bistro-2024-08-28',
    recipient: 'Savory Bites Bistro',
    category: 'Dining Out',
    date: new Date('2024-08-28'),
    amount: -55.5,
    avatarPath: '/profilePictures/Logo-6.png',
  },
  {
    id: 'daniel-carter-2024-08-27',
    recipient: 'Daniel Carter',
    category: 'Transportation',
    date: new Date('2024-08-27'),
    amount: -42.3,
    avatarPath: '/profilePictures/Person-1.jpg',
  },
  {
    id: 'sun-park-2024-08-26',
    recipient: 'Sun Park',
    category: 'Groceries',
    date: new Date('2024-08-26'),
    amount: 120,
    avatarPath: '/profilePictures/Person-10.jpg',
  },
  {
    id: 'connect-care-2024-08-25',
    recipient: 'Connect Care',
    category: 'Bills',
    date: new Date('2024-08-25'),
    amount: -80,
    avatarPath: '/profilePictures/Logo-6.png',
  },
  {
    id: 'green-grocer-2024-08-24',
    recipient: 'Green Grocer',
    category: 'Groceries',
    date: new Date('2024-08-24'),
    amount: -32.75,
    avatarPath: '/profilePictures/Person-1.jpg',
  },
  {
    id: 'luna-transit-2024-08-23',
    recipient: 'Luna Transit',
    category: 'Transportation',
    date: new Date('2024-08-23'),
    amount: -18,
    avatarPath: '/profilePictures/Person-10.jpg',
  },
  {
    id: 'harbor-market-2024-08-22',
    recipient: 'Harbor Market',
    category: 'Groceries',
    date: new Date('2024-08-22'),
    amount: -64.2,
    avatarPath: '/profilePictures/Logo-1.jpg',
  },
  {
    id: 'oak-and-ivy-2024-08-21',
    recipient: 'Oak and Ivy',
    category: 'Entertainment',
    date: new Date('2024-08-21'),
    amount: -15,
    avatarPath: '/profilePictures/Logo-6.png',
  },
  {
    id: 'maya-thompson-2024-08-20',
    recipient: 'Maya Thompson',
    category: 'Personal Care',
    date: new Date('2024-08-20'),
    amount: 50,
    avatarPath: '/profilePictures/Person-1.jpg',
  },
  {
    id: 'northstar-energy-2024-08-19',
    recipient: 'Northstar Energy',
    category: 'Bills',
    date: new Date('2024-08-19'),
    amount: -95,
    avatarPath: '/profilePictures/Person-10.jpg',
  },
]
